int hjl = (5 / 4 + 1);
int jhk = (5 *  4 - 1);
int tyb = (4 % 2);
boolean yes;
yes = 1 < 3;
print(yes);
boolean no;
no = 99 > 100;
print(no);
boolean sure =  10 >= 9;
print(sure);
boolean stillNo;
stillNo = 6 * 4 <= 8;
print(stillNo);
int number;
number = (tyb + hjl - jhk);
print(number);
boolean equal;
equal = -17 == -18 - 1;
println(equal);
boolean False;
False = true && false;
boolean True;
True = false || true;
print(False + " is not " + True);
boolean inequal;
inequal = !(-17 == -18 + 1) || (hjl != jhk);
print(inequal);
